# Generated by Django 4.2.7 on 2023-11-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("To_do", "0002_task_due_date_task_relevanse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task", name="due_date", field=models.DateField(auto_now=True),
        ),
    ]
